export const userPositionList = state => state.userPositionList
export const messageList = state => state.messageList
export const publicParameters = state => state.publicParameters
export const accountData = state => state.accountData
export const transactionDetailData = state => state.transactionDetailData
export const appCenterData = state => state.appCenterData
export const appStoreData = state => state.appStoreData
export const loggerData = state => state.loggerData
export const orderData = state => state.orderData
